# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: [
        '--ignore-words-list=reord,dout,nd,te,ser',  # Word used in error messages that need rewording
        --check-filenames,
        --check-hidden,
        ]

-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.11
    hooks:
    -   id: swiftformat
        args: [
        .,
        --swiftversion,
        '5.7',
        --verbose,
        --enable,
        'acronyms,isEmpty,preferDouble,wrapEnumCases',
        --disable,
        'redundantReturn',
        ]

-   repo: https://github.com/realm/SwiftLint
    rev: 0.47.1
    hooks:
    -   id: swiftlint
        name: SwiftLint (fix mode)
        args: [
            --fix,
        ]
    -   id: swiftlint
        name: SwiftLint
    -   id: swiftlint
        name: SwiftLint (strict mode)
        args: [ --strict ]
