# workflow 의 이름
name: Run Test

on: [push]

jobs:
#  build 체크
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Test
      run: xcodebuild build -project TodayAnbu.xcodeproj -scheme TodayAnbu -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro'  
      
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for SwiftLint (Only files changed in the PR) with --strict
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
#       env:
#         DIFF_BASE: ${{ github.base_ref }}

#   pre-commit:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - uses: pre-commit/action@v2.0.3
