# workflow 의 이름
name: Run Test

on: [push]

jobs:
  # build 체크
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build Test
      run: xcodebuild build -project AppleMusicClone.xcodeproj -scheme AppleMusicClone -destination 'platform=iOS Simulator,OS=15.4,name=iPhone 13 Pro Max'  
